### ISSUE TITLE
Error with app using Babel require hooks

### ISSUE THREAD

**Issue by tejasmanohar** [koajs/react-view#5]
Is it possible to use this module with an application that's already using Babel 6 (and the babel-polyfill for async functions and whatnot) via require hooks on the server-side? I keep getting the error `only one instance of babel/polyfill is allowed`, which does make sense since two components are loading the polyfill (runner for my app and this module). I think it'll work fine if I transpile the main application code rather than use require hooks, but then, I'd have to transpile to run/test application code in development because I'm pretty sure `babel-node` will give the same error about the polyfill.

**Comment by tejasmanohar** [comment]
Hmm, maybe this project can use Babel 6 and allow users to specify not to include the polyfill?

**Comment by tejasmanohar** [comment]
> Seems like that’s a mistake with that library. the require hook should only ever be used by the root application

I asked in BabelJS slack, here's what I got ^ - Maybe transpiling would be a better choice? Not too sure how that'd work in context. At least, IMO Babel itself shouldn't be required to use the library.

UPDATE: Another suggestion from Slack

> it seems like it should just assume that the user will have either precompiled their components, or have set up the require hook themselves

I agree with this ^. We're already telling this module the params for babel's require hook so why not just have the user use Babel. The way this is currently setup means that I can't use babel polyfill globally as a require hook in my apps nor can I differ from the babel version of this module. What do you think about this (potential) change, @dead-horse?

**Comment by dead-horse** [comment]
I'm not sure, I'm unfamiliar with babel, but let root application to require babel SGTM.

**Comment by tejasmanohar** [comment]
Sounds good. I will think about it some more and then work on a PR :)

**Comment by tejasmanohar** [comment]
@dead-horse Got it. I say give flexibility/options to the user. Submitted PR; see #6.

**Comment by tejasmanohar** [comment]
a863a0b82c29d455ed5b044f248f5302105b7523
